### ISSUE TITLE
Is the tca8418 standalone ?

### ISSUE THREAD

**Issue by wencaexige** [StephenDone/kickr_shifters#2]
Hello, awesome project, totally into it as I came by a garage sale kickr with no handlebars.

My Q: is the tiny tca8418 standalone for the final project ? Or does it still need to be hooked up to a pi ? And if it is standalone how did you program it, the python script being for the pi ? Thanks a lot and sorry if I’m missing this basic info, I know arduino and pi but missing this idea of what the 8418 encoder actually is.

**Comment by StephenDone** [comment]
As long as you wire the '8418 correctly, the KICKR configures the chip when it detects the shifter has been plugged in.
Take a look at the TCA8418 datasheet PDF to see what it does.
Sounds like my kind of garage sale!

**Comment by wencaexige** [comment]
Thanks ! That’s exactly what I was missing out, didn’t get it that the kickr itself sends data to the chip too, not just the other way around… thanks for your wiki and help.

**Comment by StephenDone** [comment]
No worries. I'm glad it was useful to someone.
